SET LINESIZE 200;
SET PAGESIZE 100;
COLUMN MENU_CD FORMAT A20;
COLUMN UP_MENU_CD FORMAT A20;
COLUMN MENU_NM FORMAT A30;
COLUMN MENU_URL FORMAT A40;
SELECT MENU_CD, UP_MENU_CD, MENU_NM, MENU_URL FROM TB_MENU WHERE MENU_CD LIKE '%CONTACT%' OR MENU_NM LIKE '%주소록%';
EXIT;
