SET LINESIZE 200;
SET PAGESIZE 100;
COLUMN COLUMN_NAME FORMAT A20;
COLUMN DATA_TYPE FORMAT A20;
SELECT COLUMN_NAME, DATA_TYPE, IDENTITY_COLUMN FROM ALL_TAB_COLUMNS WHERE TABLE_NAME = 'TB_CONTACT_GROUP' ORDER BY COLUMN_ID;
EXIT;
