SET LINESIZE 200;
SET PAGESIZE 100;
COLUMN MENU_CD FORMAT A20;
COLUMN UP_MENU_CD FORMAT A20;
COLUMN MENU_NM FORMAT A30;
COLUMN MENU_URL FORMAT A40;
SELECT A.MENU_CD, A.UP_MENU_CD, A.MENU_NM, A.MENU_URL, B.AUTH_CD 
FROM TB_MENU A 
LEFT JOIN TB_MENU_AUTH B ON A.MENU_CD = B.MENU_CD 
WHERE A.MENU_CD LIKE '%CONTACT%';
EXIT;
