whenever sqlerror exit sql.sqlcode

set echo off
set feedback off
set heading off
set pagesize 0
set linesize 32767
set long 100000000
set longchunksize 32767
set trimspool on
set verify off
set serveroutput on size unlimited

begin
  dbms_metadata.set_transform_param(dbms_metadata.session_transform, 'SQLTERMINATOR', true);
  dbms_metadata.set_transform_param(dbms_metadata.session_transform, 'PRETTY', true);
  dbms_metadata.set_transform_param(dbms_metadata.session_transform, 'SEGMENT_ATTRIBUTES', false);
  dbms_metadata.set_transform_param(dbms_metadata.session_transform, 'STORAGE', false);
  dbms_metadata.set_transform_param(dbms_metadata.session_transform, 'TABLESPACE', false);
  dbms_metadata.set_transform_param(dbms_metadata.session_transform, 'EMIT_SCHEMA', false);
end;
/

spool /tmp/sms-project-v2-project-tables.sql replace

select '-- sms-project-v2 project table SQL export' from dual;
select '-- Source schema: ' || user from dual;
select '-- Generated at: ' || to_char(systimestamp, 'YYYY-MM-DD HH24:MI:SS TZH:TZM') from dual;
select '-- Data rule: SMS_HISTORY is limited to 500 rows; other selected tables include all current rows.' from dual;
select '' from dual;
select 'set define off;' from dual;
select 'alter session set nls_date_language = ''AMERICAN'';' from dual;
select '' from dual;

select '-- Drop tables' from dual;
with target(seq, table_name) as (
  select 1, 'TB_AUTHORITY' from dual union all
  select 2, 'TB_BANK' from dual union all
  select 3, 'TB_CURRENCY' from dual union all
  select 4, 'TB_RATE_PROVIDER' from dual union all
  select 5, 'TB_DEPT' from dual union all
  select 6, 'TB_DEP' from dual union all
  select 7, 'TB_EMP' from dual union all
  select 8, 'EMPLOYEE' from dual union all
  select 9, 'TB_MENU' from dual union all
  select 10, 'TB_MENU_AUTH' from dual union all
  select 11, 'TB_CONTACT_GROUP' from dual union all
  select 12, 'TB_CONTACT' from dual union all
  select 13, 'TB_GROUP_CONTACT_MAP' from dual union all
  select 14, 'TB_MESSAGE' from dual union all
  select 15, 'CAMPAIGN' from dual union all
  select 16, 'TB_APPROVAL' from dual union all
  select 17, 'TB_APPROVAL_HIST' from dual union all
  select 18, 'TB_ATTACH_FILE' from dual union all
  select 19, 'TB_CUSTOMER_SSN' from dual union all
  select 20, 'TB_EXCHANGE_RATE' from dual union all
  select 21, 'TB_PRIVACY_AUDIT_LOG' from dual union all
  select 22, 'TB_SMS_HISTORY' from dual union all
  select 23, 'SMS_HISTORY' from dual union all
  select 24, 'SMS_SEND_LOG' from dual
)
select 'drop table "' || table_name || '" cascade constraints purge;' from target order by seq desc;

select '' from dual;
select '-- DDL' from dual;
with target(seq, table_name) as (
  select 1, 'TB_AUTHORITY' from dual union all
  select 2, 'TB_BANK' from dual union all
  select 3, 'TB_CURRENCY' from dual union all
  select 4, 'TB_RATE_PROVIDER' from dual union all
  select 5, 'TB_DEPT' from dual union all
  select 6, 'TB_DEP' from dual union all
  select 7, 'TB_EMP' from dual union all
  select 8, 'EMPLOYEE' from dual union all
  select 9, 'TB_MENU' from dual union all
  select 10, 'TB_MENU_AUTH' from dual union all
  select 11, 'TB_CONTACT_GROUP' from dual union all
  select 12, 'TB_CONTACT' from dual union all
  select 13, 'TB_GROUP_CONTACT_MAP' from dual union all
  select 14, 'TB_MESSAGE' from dual union all
  select 15, 'CAMPAIGN' from dual union all
  select 16, 'TB_APPROVAL' from dual union all
  select 17, 'TB_APPROVAL_HIST' from dual union all
  select 18, 'TB_ATTACH_FILE' from dual union all
  select 19, 'TB_CUSTOMER_SSN' from dual union all
  select 20, 'TB_EXCHANGE_RATE' from dual union all
  select 21, 'TB_PRIVACY_AUDIT_LOG' from dual union all
  select 22, 'TB_SMS_HISTORY' from dual union all
  select 23, 'SMS_HISTORY' from dual union all
  select 24, 'SMS_SEND_LOG' from dual
)
select replace(
         dbms_metadata.get_ddl('TABLE', table_name, user),
         'GENERATED ALWAYS AS IDENTITY',
         'GENERATED BY DEFAULT AS IDENTITY'
       )
from target
order by seq;

select '' from dual;
select '-- Data' from dual;

declare
  type t_table is record (
    seq number,
    table_name varchar2(128),
    row_limit number
  );
  type t_tables is table of t_table;

  l_tables t_tables := t_tables(
    t_table(1, 'TB_AUTHORITY', null),
    t_table(2, 'TB_BANK', null),
    t_table(3, 'TB_CURRENCY', null),
    t_table(4, 'TB_RATE_PROVIDER', null),
    t_table(5, 'TB_DEPT', null),
    t_table(6, 'TB_DEP', null),
    t_table(7, 'TB_EMP', null),
    t_table(8, 'EMPLOYEE', null),
    t_table(9, 'TB_MENU', null),
    t_table(10, 'TB_MENU_AUTH', null),
    t_table(11, 'TB_CONTACT_GROUP', null),
    t_table(12, 'TB_CONTACT', null),
    t_table(13, 'TB_GROUP_CONTACT_MAP', null),
    t_table(14, 'TB_MESSAGE', null),
    t_table(15, 'CAMPAIGN', null),
    t_table(16, 'TB_APPROVAL', null),
    t_table(17, 'TB_APPROVAL_HIST', null),
    t_table(18, 'TB_ATTACH_FILE', null),
    t_table(19, 'TB_CUSTOMER_SSN', null),
    t_table(20, 'TB_EXCHANGE_RATE', null),
    t_table(21, 'TB_PRIVACY_AUDIT_LOG', null),
    t_table(22, 'TB_SMS_HISTORY', null),
    t_table(23, 'SMS_HISTORY', 500),
    t_table(24, 'SMS_SEND_LOG', null)
  );

  l_sql clob;
  l_cols clob;
  l_expr clob;
  l_select clob;
  l_cursor integer;
  l_status integer;
  l_insert varchar2(32767);

  function qname(p_name varchar2) return varchar2 is
  begin
    return '"' || replace(p_name, '"', '""') || '"';
  end;
begin
  for i in 1 .. l_tables.count loop
    dbms_output.put_line(chr(10) || '-- Data for ' || l_tables(i).table_name ||
      case when l_tables(i).row_limit is null then '' else ' (limited to ' || l_tables(i).row_limit || ' rows)' end);

    l_cols := null;
    l_expr := null;

    for c in (
      select column_name, data_type
      from user_tab_columns
      where table_name = l_tables(i).table_name
      order by column_id
    ) loop
      if l_cols is not null then
        l_cols := l_cols || ', ';
        l_expr := l_expr || ' || '', '' || ';
      end if;

      l_cols := l_cols || qname(c.column_name);

      case
        when c.data_type in ('VARCHAR2', 'NVARCHAR2', 'CHAR', 'NCHAR') then
          l_expr := l_expr ||
            'case when ' || qname(c.column_name) || ' is null then ''NULL'' else chr(39) || replace(to_char(' ||
            qname(c.column_name) || '), chr(39), chr(39) || chr(39)) || chr(39) end';
        when c.data_type = 'CLOB' then
          l_expr := l_expr ||
            'case when ' || qname(c.column_name) || ' is null then ''NULL'' else ''to_clob('' || chr(39) || replace(dbms_lob.substr(' ||
            qname(c.column_name) || ', 4000, 1), chr(39), chr(39) || chr(39)) || chr(39) || '')'' end';
        when c.data_type = 'DATE' then
          l_expr := l_expr ||
            'case when ' || qname(c.column_name) || ' is null then ''NULL'' else ''to_date('' || chr(39) || to_char(' ||
            qname(c.column_name) || ', ''YYYY-MM-DD HH24:MI:SS'') || chr(39) || '','' || chr(39) || ''YYYY-MM-DD HH24:MI:SS'' || chr(39) || '')'' end';
        when c.data_type like 'TIMESTAMP%' then
          l_expr := l_expr ||
            'case when ' || qname(c.column_name) || ' is null then ''NULL'' else ''to_timestamp('' || chr(39) || to_char(' ||
            qname(c.column_name) || ', ''YYYY-MM-DD HH24:MI:SS.FF6'') || chr(39) || '','' || chr(39) || ''YYYY-MM-DD HH24:MI:SS.FF6'' || chr(39) || '')'' end';
        when c.data_type in ('NUMBER', 'FLOAT', 'BINARY_FLOAT', 'BINARY_DOUBLE') then
          l_expr := l_expr ||
            'case when ' || qname(c.column_name) || ' is null then ''NULL'' else to_char(' ||
            qname(c.column_name) || ', ''TM9'', ''NLS_NUMERIC_CHARACTERS=.,'') end';
        when c.data_type = 'RAW' then
          l_expr := l_expr ||
            'case when ' || qname(c.column_name) || ' is null then ''NULL'' else ''hextoraw('' || chr(39) || rawtohex(' ||
            qname(c.column_name) || ') || chr(39) || '')'' end';
        else
          raise_application_error(-20000, 'Unsupported data type for SQL export: ' || l_tables(i).table_name || '.' || c.column_name || ' ' || c.data_type);
      end case;
    end loop;

    l_sql := 'select ''insert into ' || qname(l_tables(i).table_name) || ' (' || l_cols || ') values ('' || ' ||
      l_expr || ' || '');'' from ';

    if l_tables(i).row_limit is null then
      l_sql := l_sql || qname(l_tables(i).table_name) || ' order by rowid';
    else
      l_sql := l_sql || '(select * from ' || qname(l_tables(i).table_name) || ' order by rowid) where rownum <= ' || l_tables(i).row_limit;
    end if;

    l_cursor := dbms_sql.open_cursor;
    dbms_sql.parse(l_cursor, l_sql, dbms_sql.native);
    dbms_sql.define_column(l_cursor, 1, l_insert, 32767);
    l_status := dbms_sql.execute(l_cursor);

    while dbms_sql.fetch_rows(l_cursor) > 0 loop
      dbms_sql.column_value(l_cursor, 1, l_insert);
      dbms_output.put_line(l_insert);
    end loop;

    dbms_sql.close_cursor(l_cursor);
  end loop;
end;
/

select '' from dual;
select 'commit;' from dual;
select '' from dual;
select '-- End of export' from dual;

spool off
exit
